#!/usr/bin/env bash
# This script: Creates the file /var/run/holbertonscript.pid containing its PID.
# Displays To infinity and beyond indefinitely.
# Displays I hate the kill command when receiving a SIGTERM signal.
# Displays Y U no love me?! when receiving a SIGINT signal.
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.
echo $$ > /var/run/holbertonscript.pid
while true
do
    trap 'echo Y U no love me?!' 2
    trap 'pgrep -f 100-process_and_pid_file | xargs kill -9 & rm -f /var/run/holbertonscript.pid' 3
    trap 'echo I hate the kill command & pgrep -f 100-process_and_pid_file | xargs kill -9 & rm -f /var/run/holbertonscript.pid' 15
    echo "To infinity and beyond indefinitely"
    sleep 2
done
