#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, using the while loop + IFS.
f="/etc/passwd"
while read -r line
do
    USERNAME=$(echo "$line" | cut -d':' -f 1)
    GROUP_ID=$(echo "$line" | cut -d':' -f 3)
    HOME_DIRECTORY=$(echo "$line" | cut -d':' -f 6)
    COMMANDSHELL=$(echo "$line" | cut -d':' -f 7)
    PASSWORD=$(echo "$line" | cut -d':' -f 2)
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMANDSHELL. $GROUP_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USERNAME"
done < $f
