#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and: displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
i=0
while [ $i -le 19 ]
do
    echo $((i + 1))
    case $i in
        3)
            echo "bad luck from China"
            ;;
        8)
            echo "bad luck from Japan"
            ;;
        16)
            echo "bad luck from Italy"
    esac
    ((i++))
done
