#!/usr/bin/env bash
# This script configures an Ubuntu server.
cp /etc/hosts ~/hosts.cpy
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.cpy
echo -e "\n8.8.8.8\tfacebook.com" >> ~/hosts.cpy
cp ~/hosts.cpy /etc/hosts
